---
- block:
  - name: Install updates
    apt: upgrade=dist update_cache=yes

  - name: Install important packages
    apt: pkg="{{ item }}" state=latest 
    with_items:
      - screen 
      - python-pip
      - git
      - wget
      - rsync
      - zip
      - vim

  become: true  
